package vista.compositor;

import controlador.ControladorPersona;
import java.util.List;
import java.util.Locale;
import javax.swing.table.DefaultTableModel;
import modelo.Cancion;
import modelo.Cantante;
import modelo.Compositor;

public class VentanaBuscarCompositor extends javax.swing.JInternalFrame {

    private ControladorPersona controladorPersona;
    
    public VentanaBuscarCompositor(ControladorPersona controladorPersona) {
        initComponents();
        this.controladorPersona = controladorPersona;
    }

    public void cambiarIdioma(Locale localizacion){
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("vista/compositor/Bundle", localizacion); // NOI18N
        
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("VentanaBuscarCompositor.jPanel3.border.title"))); // NOI18N

        jLabel5.setText(bundle.getString("VentanaBuscarCompositor.jLabel5.text")); // NOI18N

        jLabel9.setText(bundle.getString("VentanaBuscarCompositor.jLabel9.text")); // NOI18N

        jLabel10.setText(bundle.getString("VentanaBuscarCompositor.jLabel10.text")); // NOI18N

        jLabel11.setText(bundle.getString("VentanaBuscarCompositor.jLabel11.text")); // NOI18N

        jLabel12.setText(bundle.getString("VentanaBuscarCompositor.jLabel12.text")); // NOI18N

        jLabel13.setText(bundle.getString("VentanaBuscarCompositor.jLabel13.text")); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("VentanaBuscarCompositor.jPanel1.border.title"))); // NOI18N

        jLabel1.setText(bundle.getString("VentanaBuscarCompositor.jLabel1.text")); // NOI18N

        btnBuscar.setText(bundle.getString("VentanaBuscarCompositor.btnBuscar.text")); // NOI18N

        jLabel2.setText(bundle.getString("VentanaBuscarCompositor.jLabel2.text")); // NOI18N

        jLabel3.setText(bundle.getString("VentanaBuscarCompositor.jLabel3.text")); // NOI18N

        jLabel4.setText(bundle.getString("VentanaBuscarCompositor.jLabel4.text")); // NOI18N

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        spnCodigo = new javax.swing.JSpinner();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        spnEdad = new javax.swing.JSpinner();
        txtNacionalidad = new javax.swing.JTextField();
        txtSalario = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNomCancion = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        spnNumComposiciones = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCanciones = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();

        setClosable(true);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("vista/compositor/Bundle"); // NOI18N
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("VentanaBuscarCompositor.jPanel3.border.title"))); // NOI18N
        jPanel3.setToolTipText(bundle.getString("VentanaBuscarCompositor.jPanel3.toolTipText")); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText(bundle.getString("VentanaBuscarCompositor.jLabel5.text")); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel9.setText(bundle.getString("VentanaBuscarCompositor.jLabel9.text")); // NOI18N
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel10.setText(bundle.getString("VentanaBuscarCompositor.jLabel10.text")); // NOI18N
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel11.setText(bundle.getString("VentanaBuscarCompositor.jLabel11.text")); // NOI18N
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLabel12.setText(bundle.getString("VentanaBuscarCompositor.jLabel12.text")); // NOI18N
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        jLabel13.setText(bundle.getString("VentanaBuscarCompositor.jLabel13.text")); // NOI18N
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));
        jPanel3.add(spnCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 100, -1));
        jPanel3.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 160, -1));
        jPanel3.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 160, -1));
        jPanel3.add(spnEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 100, -1));
        jPanel3.add(txtNacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 160, -1));
        jPanel3.add(txtSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 160, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("VentanaBuscarCompositor.jPanel1.border.title"))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText(bundle.getString("VentanaBuscarCompositor.jLabel1.text")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 40, -1, -1));
        jPanel1.add(txtNomCancion, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 68, 180, -1));

        btnBuscar.setText(bundle.getString("VentanaBuscarCompositor.btnBuscar.text")); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, -1, -1));

        jLabel2.setText(bundle.getString("VentanaBuscarCompositor.jLabel2.text")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, -1, -1));
        jPanel1.add(spnNumComposiciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, -1, -1));

        jLabel3.setText(bundle.getString("VentanaBuscarCompositor.jLabel3.text")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel4.setText(bundle.getString("VentanaBuscarCompositor.jLabel4.text")); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        tblCanciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCanciones);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 570, 130));

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblClientes);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 560, 130));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        Compositor aux = (Compositor) controladorPersona.buscarPorNombreCancion(txtNomCancion.getText());
        spnCodigo.setValue(aux.getCodigo());
        txtNombre.setText(aux.getNombre());
        txtApellido.setText(aux.getApellido());
        spnEdad.setValue(aux.getEdad());
        txtNacionalidad.setText(aux.getNacionalidad());
        spnNumComposiciones.setValue(aux.getNumeroDeComposiciones());
        cargarTablaCanciones(aux.getCancionesTop100Billboard());
        cargarTablaClientes(aux.getClientes());
        txtSalario.setText(aux.getSalario()+"");
    }//GEN-LAST:event_btnBuscarActionPerformed

    
    private void cargarTablaCanciones(List<Cancion> canciones) {
        DefaultTableModel modelo = new DefaultTableModel(new Object[]{"Código","Titulo","Duración"}, 0);
        for (Cancion c:  canciones) {
            int codigo = c.getCodigo();
            String nombre = c.getTitulo();
            double tiempo = c.getTiempoEnMinutos();
            Object[] rowData = {codigo, nombre, tiempo};
            modelo.addRow(rowData);
        }
        this.tblCanciones.setModel(modelo);
    }
    
    private void cargarTablaClientes(List<Cantante> clientes) {
        DefaultTableModel modelo = new DefaultTableModel(new Object[]{"Nombre","Apellido","Nom. Artístico"}, 0);
        for (Cantante c:  clientes) {
            String artistico = c.getNombreArtistico();
            String nombre = c.getNombre();
            String apellido = c.getApellido();
            Object[] rowData = {nombre, apellido, artistico};
            modelo.addRow(rowData);
        }
        this.tblClientes.setModel(modelo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner spnCodigo;
    private javax.swing.JSpinner spnEdad;
    private javax.swing.JSpinner spnNumComposiciones;
    private javax.swing.JTable tblCanciones;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtNacionalidad;
    private javax.swing.JTextField txtNomCancion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSalario;
    // End of variables declaration//GEN-END:variables
}
